[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cmme"
version = "2023.09a"
requires-python = ">=3.10"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
